using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Flora.Services.Database;

namespace Flora.Services.Database.Seeders
{
    public static class ProductSeeder
    {
        public static void SeedData(this EntityTypeBuilder<Product> entity)
        {
            entity.HasData(

                new Product { Id = 1, Name = "Welcome Baby Girl", Description = "Flowers beautifully arranged in a box for newborn baby", Price = 60.00m, CategoryId = 5, OccasionId = 2, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 2, Name = "Welcome Baby Boy", Description = "Flowers beautifully arranged in a box for newborn baby", Price = 60.00m, CategoryId = 5, OccasionId = 2, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 3, Name = "Happy Birthday Queen", Description = "Luxury rosegold bouquet with 101 rose in mixed colors for our birthday queens", Price = 150.00m, CategoryId = 1, OccasionId = 1, IsNew = true, IsFeatured = true, Active = true, IsAvailable = true },
                new Product { Id = 4, Name = "Blue Tulip Elegance", Description = "A stunning bouquet of 20 exquisite blue tulips, hand-picked at peak bloom for their rich sapphire hue. Accented with delicate white waxflowers and soft silver eucalyptus leaves, " +
                "this arrangement brings a cool, serene elegance to any space, perfect for those who appreciate rare beauty and timeless style.", Price = 80.00m, CategoryId = 1, OccasionId = 2, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 5, Name = "Eternal Blossom Box", Description = "An opulent arrangement featuring over 50 hand-selected blooms, including velvety red roses, fragrant gardenias, delicate lilies, and soft spray carnations.", Price = 180.00m, CategoryId = 5, OccasionId = 1, IsNew = true, IsFeatured = true, Active = true, IsAvailable = true },
                new Product { Id = 6, Name = "Serenity Blue Box", Description = "A luxurious gift box featuring a lush blue hydrangea centerpiece surrounded by delicate white baby's breath and sprigs of fresh greenery.", Price = 100.00m, CategoryId = 5, OccasionId = 2, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 7, Name = "Blush Elegance Box", Description = "A charming gift box filled with a stunning mix of soft pink roses, delicate peonies, and lush ranunculus blooms.", Price = 90.00m, CategoryId = 5, OccasionId = 1, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 8, Name = "Pure Serenity Box", Description = "Elegant box filled with pristine white roses symbolizing purity and grace, complemented by delicate white lilies and soft greenery", Price = 80.00m, CategoryId = 5, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 9, Name = "Flower Box Deluxe", Description = "Elegant box with 20 red roses", Price = 70.00m, CategoryId = 5, OccasionId = null, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 10, Name = "Blush Heart Box", Description = "A romantic heart-shaped box overflowing with lush, velvety pink roses, symbolizing love and admiration.", Price = 120.00m, CategoryId = 5, OccasionId = 1, IsNew = true, IsFeatured = true, Active = true, IsAvailable = true },
                new Product { Id = 11, Name = "Cactus", Description = "A resilient beauty with minimal care needs, this spiky companion adds a touch of desert magic and modern style to any space.", Price = 18.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 12, Name = "Cornplant", Description = "With its tall, graceful stalks and lush, arching green leaves, the Corn Plant brings a tropical vibe and elegant greenery to any interior. ", Price = 25.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 13, Name = "Elegant White Dahlias Bouquet", Description = "Gracefully arranged white dahlias nestled in a serene blue bouquet, creating a perfect harmony of purity and calm. ", Price = 60.00m, CategoryId = 1, OccasionId = 2, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 14, Name = "Golden Hour Dome", Description = "A warm mix of golden roses and amber-colored wildflowers under a glass dome", Price = 100.00m, CategoryId = 3, OccasionId = null, IsNew = false, IsFeatured = true, Active = true, IsAvailable = true },
                new Product { Id = 15, Name = "The Enchanted Garden Dome", Description = "A magical blend of fresh roses, lavender sprigs, and eucalyptus leaves artfully enclosed in a crystal-clear glass dome.", Price = 70.00m, CategoryId = 3, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 16, Name = "Midnight Bloom Dome", Description = "A single, stunning blue rose preserved under a crystal-clear glass dome. Symbolizing mystery and rarity.", Price = 40.00m, CategoryId = 3, OccasionId = null, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 17, Name = "Winter Wonderland Dome", Description = "Elegant dome perfect for the holiday season.", Price = 70.00m, CategoryId = 3, OccasionId = null, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 18, Name = "Birthday Bliss Dome", Description = "This dome bouquet brings joy and festive charm to any birthday celebration. Perfect as a memorable gift that lasts.", Price = 60.00m, CategoryId = 3, OccasionId = 1, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 19, Name = "Garden Symphony Bouquet", Description = "A stunning medley of roses, gerberas, and seasonal blooms, expertly arranged to create a harmonious explosion of color and fragrance.", Price = 60.00m, CategoryId = 1, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 20, Name = "Spring Awakening Mix", Description = "An exuberant gathering of seasonal blooms: daffodils, hyacinths, ranunculus, and freesias,", Price = 40.00m, CategoryId = 1, OccasionId = null, IsNew = true, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 21, Name = "Pink Bloosom Bouquet", Description = "A bouquet of fresh pink flowers.", Price = 50.00m, CategoryId = 1, OccasionId = 1, IsNew = true, IsFeatured = true, Active = true, IsAvailable = true },
                new Product { Id = 22, Name = "Pink Delight Bouquet", Description = "A cheerful arrangement featuring soft pink gerberas and fresh white daisies", Price = 35.00m, CategoryId = 1, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 23, Name = "Achievement Celebration Bouquet", Description = " With 30 red roses, this bouquet captures the pride and happiness of a milestone reached.", Price = 135.00m, CategoryId = 1, OccasionId = 3, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 24, Name = "Graduation Glory Mix", Description = "A colorful medley of roses, tulips, and daisies in bold and bright hues, designed to inspire and celebrate this momentous occasion.", Price = 75.00m, CategoryId = 1, OccasionId = 3, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 25, Name = "Graduation Celebration Mix", Description = "A colorful medley of roses, tulips, and daisies in bold and bright hues, designed to inspire and celebrate this momentous occasion.", Price = 75.00m, CategoryId = 1, OccasionId = 3, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 26, Name = "Bright Future Blossoms", Description = "A cheerful arrangement featuring soft pink roses, designed to inspire and celebrate this moments.", Price = 95.00m, CategoryId = 5, OccasionId = 3, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 27, Name = "Ocean Breeze Hydrangea", Description = "Delicate blue hydrangea blooms evoke the refreshing coolness of ocean waves.", Price = 45.00m, CategoryId = 1, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 28, Name = "Palm", Description = "Bring a touch of the tropics into your home with this elegant palm.", Price = 25.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 29, Name = "Peace Lilly", Description = "Known for its glossy leaves and delicate white blooms, the Peace Lily purifies your air while adding a serene and peaceful vibe to your living space.", Price = 20.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 30, Name = "Philodendron", Description = "With lush, heart-shaped leaves, the Philodendron adds a vibrant splash of green and effortless style.", Price = 20.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 31, Name = "Pink Lillies Bouquet", Description = "Bright and cheerful tulips bouquet", Price = 40.00m, CategoryId = 1, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 32, Name = "Pink Tulips Bouquet", Description = "Bright and cheerful tulips bouquet.", Price = 35.00m, CategoryId = 1, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 33, Name = "Purple Tulips Bouquet", Description = "Bright and cheerful tulips bouquet.", Price = 35.00m, CategoryId = 1, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 34, Name = "Red Roses Bouquet", Description = "Bright and cheerful red roses bouquet.", Price = 5.00m, CategoryId = 1, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 35, Name = "Snake Plant", Description = "A hardy and architectural beauty, the Snake Plant features tall, upright leaves with striking variegation.", Price = 25.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 36, Name = "Spider Plant", Description = "With its arching, striped leaves and cascading baby “spiders,” this lively plant brings dynamic energy and a fresh vibe to any room..", Price = 35.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 37, Name = "Suculents ", Description = "Compact and resilient, this succulent boasts fleshy leaves in vibrant shades", Price = 35.00m, CategoryId = 2, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 38, Name = "Eternal Elegance", Description = "A timeless bouquet featuring pristine white roses and delicate peonies, symbolizing everlasting love and grace.", Price = 55.00m, CategoryId = 7, OccasionId = null, IsNew = false, IsFeatured = true, Active = true, IsAvailable = true },
                new Product { Id = 39, Name = "Blushing Bride", Description = "An opulent arrangement of blush roses, cream dahlias, and eucalyptus — a perfect statement of lavish celebration.", Price = 65.00m, CategoryId = 7, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 40, Name = "Pure Grace", Description = "Elegant white calla lilies, known for their purity and refined beauty.", Price = 45.00m, CategoryId = 7, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 41, Name = "Winter bride", Description = "A refined bouquet of long-stemmed calla lilies, gently complemented by red roses", Price = 55.00m, CategoryId = 7, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 42, Name = "Dreamy Dew", Description = "A fresh and airy bouquet with dew-kissed ranunculus and white lisianthus,", Price = 30.00m, CategoryId = 7, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 43, Name = "Golden Hour", Description = "Capture the warmth of golden moments with this curated box of florals, fine confections, and timeless keepsakes.", Price = 145.00m, CategoryId = 6, OccasionId = 1, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 44, Name = "Pure Indulgence", Description = "Overflowing with elegant flowers and premium goodies, this box delivers an unforgettable sensory experience.", Price = 135.00m, CategoryId = 6, OccasionId = 1, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 45, Name = "Amour Box ", Description = "A romantic ensemble of roses, chocolate truffles, and a hint of fragrance – a heartfelt gift for someone special.", Price = 135.00m, CategoryId = 6, OccasionId = 1, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 46, Name = "Serenity Set ", Description = "A calming mix of greenery, soft blooms, and wellness items – perfect for relaxation and self-care.", Price = 150.00m, CategoryId = 6, OccasionId = 1, IsNew = false, IsFeatured = true, Active = true, IsAvailable = true },
                new Product { Id = 47, Name = "Midnight Bloom", Description = "Mystical and enchanting, this box blends deep-toned florals with luxurious gifts for a bold expression of love.", Price = 150.00m, CategoryId = 6, OccasionId = 1, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },

                new Product { Id = 48, Name = "Gerber", Description = ".", Price = 4.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 49, Name = "Baby's Breath", Description = ".", Price = 2.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 50, Name = "Lilly", Description = ".", Price = 3.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 51, Name = "Margarita", Description = ".", Price = 5.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 52, Name = "Tulip", Description = ".", Price = 5.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 53, Name = "Rose", Description = ".", Price = 7.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 54, Name = "Daisy", Description = ".", Price = 4.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 55, Name = "Hydrangea", Description = ".", Price = 8.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true },
                new Product { Id = 56, Name = "Calla Lilly", Description = ".", Price = 6.00m, CategoryId = 4, OccasionId = null, IsNew = false, IsFeatured = false, Active = true, IsAvailable = true }



            );
        }
    }
}
